### ISSUE TITLE
stuck with the QT problem

### ISSUE THREAD

**Issue by RanDing2000** [robot-learning-freiburg/MoMa-LLM#4]
Hi, I run the code locally not docker. And I have been stuck with the qt package for a long time. The error message says: qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/usr/stud/dira/miniconda3/envs/moma-llm/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)

Do you have any suggestions?

**Comment by dHonerkamp** [comment]
Hi,

This should be issue with the X11-forwarding. Do you run this on a remote server?
Sometimes this also helps: 
- `export XAUTHORITY=$HOME/.Xauthority`
- make sure your DISPLAY env variable is correct (you do need a display on the machine, otherwise see headless below)
- if on a remote server, connect with X11 forwarding, test that it works with some application such as `xclock`

Otherwise, have you tried running it with docker?

Alternatively, you can also just run everything headless by changing this line https://github.com/robot-learning-freiburg/MoMa-LLM/blob/5db816cf4da6217eb55bf75fb14930c467804681/moma_llm/env/env.py#L315
and then just log the image output of the simulator if you need them

**Comment by martinbchnr** [comment]
To add to this, I also observed this problem a couple of times and got around it by running `xhost +local:root` or `sudo xhost +` on your host system.
